email_login_user: youremailaddress@gmail.com
email_login_password: yourpassword
email_from: Your Name <youremailaddress@gmail.com>
email_to: Their Name <theiremailaddress@gmail.com>
email_subject: KGS - Tournament Results
email_server: smtp.gmail.com
email_port: 587
logfile: /var/log/kgs_tournament.log
timezone: timeZone="Africa/Johannesburg"
game_key: 'searches_for_this_word_in_game_comments'
dateformat: '%m/%d/%Y'
timeformat: '%I:%M %p'
