email_login_user: youremailaddress@gmail.com
email_login_password: yourpassword
email_from: Your Name <youremailaddress@gmail.com>
email_to: Their Name <theiremailaddress@gmail.com>
email_subject: KGS - Tournament Results
email_server: smtp.gmail.com
email_port: 587
logfile: /var/log/kgs_tournament.log
lastrun: 2013-08-19 22:17:07.850085
timezone: timeZone="Africa/Johannesburg"
